name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel running workflows
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '20'
      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install
      - name: Run tests
        run: pnpm test
